#!/bin/bash
# License 2021 danrobi, gpl v3
# Credit: Roland Latour http://user.cavenet.com/rolandl/yad-timer.txt
# if there is a 1st parameter, use it, else assume 3 minutes
if test -z "$1"; then
  LIMIT=180
  LABEL="Tea_Timer"
else
  LIMIT=$1
# force mathematical evaluation, for syntax: timer minutes*60
   let LIMIT=($LIMIT * 1)
# eliminates error message: "integer expression expected"
# getting strange results with leading zeros
  let min=($LIMIT / 60)
  LABEL=$min"_Minute_Timer"
fi

# if there is a 2nd parameter, use it as LABEL
if test -z "$2"; then
  true
else
  LABEL=$2
  LABEL=`echo $LABEL|sed 's/ /_/g'`
fi
#=======Start timing==========
(
for ((a=$LIMIT; a > 0; a--)); do
# compute Hrs/Mins/Secs
  let hour=($a / 3600)
  let y=($hour * 60)
  let min=($a / 60)
  let min=($min - $y)
  let y=($y * 60)
  let z=($min * 60)
  let sec=($a - $y - $z)
# compute percentage of limit time, update progress bar
  let y=($LIMIT - $a)
  let y=($y * 100)
  let pct=($y / $LIMIT)
  echo $pct;sleep 0.99
# off by 7 seconds in 3 hours
done
echo 100;echo "# $LABEL complete"
# Notification area
notify-send --urgency=low "$LABEL complete"
# beep -f 1000 -n -f 2000 -n -f 1500 &
# espeak "$LABEL has completed"
# aplay -q ~/save/waves/cowbell.wav
)

